hellowrld/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('website.urls', namespace = 'website')),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.urls import path
from .views import (
    IndexTemplateView,
    FuncionarioCreateView,
    FuncionarioListView,
    FuncionarioUpdateView,
    FuncionarioDeleteView
)

app_name = 'website'

urlpatterns = [
    path("", IndexTemplateView.as_view(), name="index"),
    path("funcionarios/novo/", FuncionarioCreateView.as_view(), name="cadastro_funcionario"),
    path(
        "funcionarios/",
        FuncionarioListView.as_view(),
        name="lista_funcionarios"
    ),
    path(
        "funcionarios/<int:pk>/atualizar/",
        FuncionarioUpdateView.as_view(),
        name="atualiza_funcionario"
    ),
    path(
        "funcionario/excluir/<int:pk>/",
        FuncionarioDeleteView.as_view(),
        name="deleta_funcionario",
    ),

]

website/models.py
from django.db import models

# Create your models here.

class Funcionario(models.Model):
    nome = models.CharField(
        max_length=255,
        null=False,
        blank=False
    )
    sobrenome = models.CharField(
        max_length = 255,
        null  = False,
        blank = False
    )
    cpf = models.CharField(
        max_length = 14,
        null = False,
        blank = False

    )
    tempo_de_servico = models.IntegerField(
        default = 0,
        null = False,
        blank = False
    )
    remuneracao = models.DecimalField(
        max_digits = 8,
        decimal_places = 2 ,
        null = False,
        blank = False
    )

    objetos = models.Manager()

website/forms.py
from django import forms
from .models import Funcionario

class InsereFuncionarioForm(forms.ModelForm):
    class Meta:
        model = Funcionario
        fields = [
            'nome',
            'sobrenome',
            'cpf',
            'tempo_de_servico',
            'remuneracao'
        ]

website/views.py
from django.views.generic import (
    TemplateView,
    CreateView,
    ListView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy

from .models import Funcionario
from .forms import InsereFuncionarioForm


class IndexTemplateView(TemplateView):
    template_name = "website/index.html"


class FuncionarioCreateView(CreateView):
    model = Funcionario
    form_class = InsereFuncionarioForm
    template_name = "website/cadastro-funcionario.html"
    success_url = reverse_lazy("website:lista_funcionarios")


class FuncionarioListView(ListView):
    model = Funcionario
    template_name = "website/lista.html"
    context_object_name = "funcionarios"


class FuncionarioUpdateView(UpdateView):
    model = Funcionario
    form_class = InsereFuncionarioForm
    template_name = "website/atualiza.html"
    success_url = reverse_lazy("website:lista_funcionarios")
class FuncionarioDeleteView(DeleteView):
    model = Funcionario
    template_name = "website/exclui.html"
    success_url = reverse_lazy("website:lista_funcionarios")
    context_object_name = "funcionario"

website/templates/website/_layouts/base.html
<!DOCTYPE html>
<html lang="pt-br">
{% load static %}
{% load tempo_atual %}

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Gerenciador de Funcionários{% endblock %}</title>

    <!-- Bootstrap CSS (CDN) -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" rel="stylesheet">

    {% block styles %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
    <a class="navbar-brand" href="{% url 'website:index' %}">
        Página Inicial
    </a>

    <button class="navbar-toggler" type="button" data-toggle="collapse"
            data-target="#conteudo-navbar"
            aria-controls="conteudo-navbar"
            aria-expanded="false"
            aria-label="Ativar navegação">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="conteudo-navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'website:index' %}">
                    Funcionários
                </a>
            </li>
        </ul>
           <!-- 👇 AQUI entra a HORA -->
        <ul class="navbar-nav float-right">
            <li class="nav-item">
                <a class="nav-link" href="#">
                    <b>Hora:</b> {% tempo_atual %}
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block conteudo %}{% endblock %}

<!-- JS -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>

{% block scripts %}{% endblock %}
</body>
</html>

website/templates/website/atualiza.html
{% extends "website/_layouts/base.html" %}
{% load widget_tweaks %}
{% block title %}Atualização de Funcionário{% endblock %}

{% block conteudo %}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-lg-10 col-md-12 col-sm-12">
            <div class="card">
                <div class="card-body">

                    <h5 class="card-title mb-4">
                        Atualiza Dados do <code>Funcionário</code>
                    </h5>

                    <form method="post">
                        {% csrf_token %}

                        <!-- Nome -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome</span>
                            </div>
                            {% render_field form.nome class+="form-control" %}
                        </div>

                        <!-- Sobrenome -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Sobrenome</span>
                            </div>
                            {% render_field form.sobrenome class+="form-control" %}
                        </div>

                        <!-- CPF -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CPF</span>
                            </div>
                            {% render_field form.cpf class+="form-control" %}
                        </div>

                        <!-- Tempo de Serviço -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Tempo de Serviço</span>
                            </div>
                            {% render_field form.tempo_de_servico class+="form-control" %}
                        </div>

                        <!-- Remuneração -->
                        <div class="input-group mb-4">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Remuneração</span>
                            </div>
                            {% render_field form.remuneracao class+="form-control" %}
                        </div>

                        <!-- Botões -->
                        <div class="text-right">
                            <a href="{% url 'website:lista_funcionarios' %}" class="btn btn-outline-secondary mr-2">
                                Voltar
                            </a>
                            <button type="submit" class="btn btn-primary">
                                Enviar
                            </button>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

website/templates/website/cadastro-funcionario.html
{% extends "website/_layouts/base.html" %}
{% load widget_tweaks %}

{% block title %}Cadastro de Funcionários{% endblock %}

{% block conteudo %}
<div class="container">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Cadastro de Funcionário</h5>
                    <p class="card-text">
                        Complete o formulário abaixo para cadastrar
                        um novo <code>Funcionário</code>.
                    </p>

                    <form method="post">
                        {% csrf_token %}

                        <!-- Nome -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Nome</span>
                            </div>
                            {% render_field form.nome class+="form-control" %}
                        </div>

                        <!-- Sobrenome -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Sobrenome</span>
                            </div>
                            {% render_field form.sobrenome class+="form-control" %}
                        </div>

                        <!-- CPF -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">CPF</span>
                            </div>
                            {% render_field form.cpf class+="form-control" %}
                        </div>

                        <!-- Tempo de Serviço -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Tempo de Serviço</span>
                            </div>
                            {% render_field form.tempo_de_servico class+="form-control" %}
                        </div>

                        <!-- Remuneração -->
                        <div class="input-group mb-3">
                            <div class="input-group-prepend">
                                <span class="input-group-text">Remuneração</span>
                            </div>
                            {% render_field form.remuneracao class+="form-control" %}
                        </div>

                        <div class="mt-3">
                            <a href="{% url 'website:index' %}" class="btn btn-outline-secondary">
                                Voltar
                              </a>

                            <button class="btn btn-primary">
                                 Enviar
                            </button>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/exclui.html
{% extends "website/_layouts/base.html" %}

{% block title %}Página Inicial{% endblock %}

{% block conteudo %}
<div class = "container mt-5">
    <div class = "card">
        <div class ="card-body">
            <h5 class = "card-title">Exclusão de funcionário</h5>
            <p class = "card-text">
                Você tem certeza de que quer excluir o funcionário <b>{{funcionario.nome}}</b>?
            </p>
            <form method = "post">
                {% csrf_token %}
                <hr />
                <div class = "text-right">
                    <a href = "{% url 'website:lista_funcionarios' %}" class = "btn btn-outline-danger">
                        Cancelar
                    </a>
                   <button class = "btn btn-danger">Excluir</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/index.html
{% extends "website/_layouts/base.html" %}

{% block title %}Página Inicial{% endblock %}

{% block conteudo %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Cadastrar Funcionário</h5>
                    <p class="card-text">Cadastre aqui um novo Funcionário.</p>
                    <a href="{% url 'website:cadastro_funcionario' %}" class="btn btn-primary">
                        Novo Funcionário
                    </a>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Lista de Funcionários</h5>
                    <p class="card-text">Veja aqui a lista de funcionários cadastrados.</p>
                    <a href="{% url 'website:lista_funcionarios' %}" class="btn btn-secondary">Va para Lista</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

website/templates/website/lista.html
{% extends "website/_layouts/base.html" %}

{% load primeira_letra %}

{% block title %}Lista de Funcionários{% endblock %}

{% block conteudo %}
<div class="container">
    <div class="row">
        <div class="col-lg-12">

            <div class="card">
                <div class="card-body">

                    <div class="d-flex justify-content-between align-items-center mb-3">
                        <h5 class="card-title mb-0">Lista de Funcionários</h5>
                    </div>

                    {% if funcionarios %}
                        <p class="card-text">
                            Aqui está a lista de <code>Funcionários</code> cadastrados.
                        </p>

                        <table class="table table-bordered table-hover">
                            <thead class="thead-dark">
                                <tr>
                                    <th class="text-center">#</th>
                                    <th>Nome</th>
                                    <th>Sobrenome</th>
                                    <th>Tempo de Serviço</th>
                                    <th>Remuneração</th>
                                    <th class="text-center">Ações</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for f in funcionarios %}
                                    <tr>
                                        <!-- Primeira letra -->
                                        <td class="text-center">
                                            {{ f.nome|primeira_letra }}
                                        </td>

                                        <td>{{ f.nome }}</td>
                                        <td>{{ f.sobrenome }}</td>
                                        <td>{{ f.tempo_de_servico }}</td>
                                        <td>R$ {{ f.remuneracao }}</td>

                                        <td class="text-center">
                                            <a
                                                href="{% url 'website:atualiza_funcionario' pk=f.id %}"
                                                class="btn btn-info btn-sm"
                                            >
                                                Atualizar
                                            </a>

                                            <a
                                                href="{% url 'website:deleta_funcionario' pk=f.id %}"
                                                class="btn btn-outline-danger btn-sm"
                                            >
                                                Excluir
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                                    <a href="{% url 'website:cadastro_funcionario' %}" class="btn btn-success">
                                    + Adicionar Funcionário
                                    </a>

                    {% else %}
                        <div class="text-center mt-5 mb-5">
                            <h5>Nenhum <code>Funcionário</code> cadastrado ainda.</h5>
                        </div>
                    {% endif %}

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}